os:
  - linux
  - osx
  - windows
sudo: false
language: go
go_import_path: l7e.io/semver
go:
  - 1.13.x
  - 1.14.x
before_install:
  - >
    if [ $TRAVIS_GO_VERSION =~ ^1\.13 -a "$TRAVIS_OS_NAME" = 'linux' ]; then
      go get -u github.com/golangci/golangci-lint/cmd/golangci-lint@v1.24.0
    fi
  - go install github.com/mattn/goveralls
script:
  - >
    if [ $TRAVIS_GO_VERSION =~ ^1\.13 -a "$TRAVIS_OS_NAME" = 'linux' ]; then
      $GOPATH/bin/golangci-lint run || true; # https://github.com/golangci/golangci-lint/issues/824
      $GOPATH/bin/golangci-lint run ;
    fi
  - $GOPATH/bin/goveralls -service=travis-ci -race -v
after_success:
  - bash <(curl -s https://codecov.io/bash)
